# Generated by Django 3.0.3 on 2020-10-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_game_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_transformation',
            field=models.BooleanField(default=False),
        ),
    ]
