# Generated by Django 3.0.3 on 2020-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_game_has_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
