# Generated by Django 2.1.7 on 2019-09-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190902_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='in project', max_length=255),
        ),
    ]
