# Generated by Django 2.1.7 on 2019-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190904_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_turn',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='INVITED', max_length=255),
        ),
    ]
